# Generated by Django 4.2.16 on 2024-09-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("length", models.FloatField(default=0.0)),
                ("opening_hours", models.TimeField(default="00:00:00")),
                ("closing_hours", models.TimeField(default="23:00:00")),
            ],
        ),
        migrations.CreateModel(
            name="Traffic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("1", "MONDAY"),
                            ("2", "TUESDAY"),
                            ("3", "WEDNESDAY"),
                            ("4", "THURSDAY"),
                            ("5", "FRIDAY"),
                            ("6", "SATURDAY"),
                            ("7", "SUNDAY"),
                        ],
                        max_length=1,
                    ),
                ),
                ("from_time", models.TimeField(default="00:00:00")),
                ("to_time", models.TimeField(default="23:00:00")),
                ("peak_hours", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("locality", models.CharField(blank=True, max_length=100, null=True)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("rating", models.FloatField(default=0.0)),
                ("is_junction", models.BooleanField(default=False)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stations",
                        to="metro.line",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("peak_hours_price", models.FloatField(default=0.0)),
                ("off_peak_hours_price", models.FloatField(default=0.0)),
                ("daily_cap", models.FloatField(default=0.0)),
                ("weekly_cap", models.FloatField(default=0.0)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination",
                        to="metro.line",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source",
                        to="metro.line",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.CharField(blank=True, max_length=100, null=True)),
                ("time", models.TimeField()),
                ("fare", models.FloatField()),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_destination",
                        to="metro.line",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_source",
                        to="metro.line",
                    ),
                ),
            ],
        ),
    ]
