# Generated by Django 4.2.16 on 2024-09-28 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("metro", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journey",
            name="time",
        ),
        migrations.AddField(
            model_name="journey",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
